### ISSUE TITLE
A question about the polyline equivalent permutations

### ISSUE THREAD

**Issue by MalignusCN** [hustvl/MapTR#1]
刚刚阅读了我们这篇论文，里面的结果感觉非常的好。这里有一个问题想请教一下，论文当中提到两个相向车道间的车道线，他的direction很难做区分.我们的formulation中，是将所有的车道线都改为了两种排列方式。那这种改变是否会对两个相同方向车道间的车道线学习造成困扰？我们是否有统计过对于整个nuScenes数据集中相向车道间车道线比例与相同方向车道间车道线的比例？感谢~

I've just read the paper on arxiv, and the results in it is really impressive. Here is a question I want to ask. The paper mentions the divider between two opposite lanes. The direction is difficult to distinguish, in your formulation, all dividers(polyline) are changed to two permutations. Will this change cause trouble for divider learning between two lanes in the same direction? Have we counted the ratio of dividers between opposing lanes to the ratio of dividers between lanes in the same direction for the entire nuScenes dataset?

**Comment by LegendBC** [comment]
Hi @MalignusCN,  thanks for your interest in our work and good question!

nuScenes does not provide annotations about the physical direction of lane dividers, so the proposed permutation-based modeling will not incur trouble for learning, and we can not count the ratio of lane dividers between opposing lanes to the ratio of lane dividers between lanes in the same direction.

If you want to apply MapTR on your custom dataset, which provides the physical direction for some polyline-based map elements, you can use MapTR with vanilla modeling (Fig. 3 vanilla) for directed polyline-based map elements and proposed permutation-based modeling for polygon- and polyline- based map elements without physical direction during training.

Since nuScenes does not provide the direction information for polyline-based map elements, we apply unified modeling to all map elements.

**Comment by MalignusCN** [comment]
> Hi @MalignusCN, thanks for your interest in our work and good question!
> 
> nuScenes does not provide annotations about the physical direction of lane dividers, so the proposed permutation-based modeling will not incur trouble for learning, and we can not count the ratio of lane dividers between opposing lanes to the ratio of lane dividers between lanes in the same direction.
> 
> If you want to apply MapTR on your custom dataset, which provides the physical direction for some polyline-based map elements, you can use MapTR with vanilla modeling (Fig. 3 vanilla) for directed polyline-based map elements and proposed permutation-based modeling for polygon- and polyline- based map elements without physical direction during training.
> 
> Since nuScenes does not provide the direction information for polyline-based map elements, we apply unified modeling to all map elements.

Thanks for your reply~
