### ISSUE TITLE
GT labels for evaluation

### ISSUE THREAD

**Issue by TonyXuQAQ** [hustvl/MapTR#36]
Thanks for sharing the great work!

When you do evaluation after inference, it seems that you used the evenly sampled GT labels for evaluation (i.e., with ```eval_use_same_gt_sample_num_flag``` as True). Is this correct? If so, may I know whether setting ```eval_use_same_gt_sample_num_flag``` as False would affect the final AP score? Since I think it would be more appropriate to use the raw GT labels without sampling for evaluation, just like VectorMapNet.

Thanks for your consideration.

**Comment by LegendBC** [comment]
We follow the paper of VectorMapNet to sample the GT, and here is their [implementation](https://github.com/Mrmoore98/VectorMapNet_code/blob/mian/plugin/datasets/evaluation/precision_recall/average_precision_gen.py#L101-L109), as you can see they also sampled the GT instance to 100 points as stated in their paper.

**Comment by LegendBC** [comment]
The false `eval_use_same_gt_sample_num_flag` is only used in we directly predict 100 points for each instance, so we do not need to interpolate the prediction to save time.

**Comment by LegendBC** [comment]
> 



> Thanks for sharing the great work!
> 
> When you do evaluation after inference, it seems that you used the evenly sampled GT labels for evaluation (i.e., with `eval_use_same_gt_sample_num_flag` as True). Is this correct? If so, may I know whether setting `eval_use_same_gt_sample_num_flag` as False would affect the final AP score? Since I think it would be more appropriate to use the raw GT labels without sampling for evaluation, just like VectorMapNet.
> 
> Thanks for your consideration.

We agree with you that the GT labels should be continuous shape instead of discrete sampled points, so we also implement another metric for our own use [here](https://github.com/hustvl/MapTR/blob/main/projects/mmdet3d_plugin/datasets/map_utils/tpfp_chamfer.py#L16). But to align the comparison metric with previous work, we have not reported the results on this [boundary IOU metric](https://arxiv.org/abs/2103.16562). But for the convenience of the community, we will report the related results in this month.

**Comment by TonyXuQAQ** [comment]
Thanks for your quick reply! I have no further questions.
